#version: '3.9'
services:
  # --- MongoDB ---
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # --- RabbitMQ ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # RabbitMQ main connection
      - "15672:15672"    # RabbitMQ management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  # --- Auth Service ---
  auth:
    build: ./auth
    container_name: auth
    ports:
      - "3000:3000"
    env_file:
      - ./auth/.env
    depends_on:
      - mongodb

  # --- Product Service ---
  product:
    build: ./product
    container_name: product
    ports:
      - "3001:3001"
    env_file:
      - ./product/.env
    #depends_on:
    #  - mongodb
    #  - rabbitmq
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  # --- Order Service ---
  order:
    build: ./order
    container_name: order
    ports:
      - "3002:3002"
    env_file:
      - ./order/.env
    #depends_on:
    #  - mongodb
    #  - rabbitmq
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  # --- API Gateway ---
  api-gateway:  
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3003:3003"
    env_file:
      - ./api-gateway/.env
    #depends_on:
    #  - auth
    #  - product
    #  - order
    depends_on:
      auth:
        condition: service_started
      product:
        condition: service_started
      order:
        condition: service_started
        
volumes:
  mongo_data:

